[global]
showWarningOnDirectExecution=false

[theme]
primaryColor="#04c9b7"
backgroundColor="#1c1c1f"
secondaryBackgroundColor="#252529"
textColor="#eeeeee"

[server]
port=8501
headless=true

[browser]
serverPort = 8501
